import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Examples',
      items: ['examples/basic-chart'],
    },
  ],
  apiSidebar: [
    'api/intro',
    {
      type: 'category',
      label: 'Guides',
      items: ['guides/SamplingDistributionsGuide'],
    },
    {
      type: 'category',
      label: 'Containers',
      items: [{ type: 'autogenerated', dirName: 'api/containers' }],
    },
    {
      type: 'category',
      label: 'Components',
      items: [
        'api/components/ToolbarComponent',
        'api/components/CaseTableComponent',
        'api/components/SummaryViewComponent',
        'api/components/LegendComponent',
        {
          type: 'category',
          label: 'Case Card & Attributes',
          items: [
            'api/components/CaseCardComponent',
            'api/components/AttributeListComponent',
            {
              type: 'category',
              label: 'Attribute Editor',
              items: [
                'api/components/AttributeEditComponent',
                'api/components/NameDescEditComponent',
                'api/components/DataTypeComponent',
                'api/components/RangeFilterComponent',
                'api/components/NumericalColorPickerComponent',
                'api/components/CategoricalColorEditor',
                'api/components/SortOrderComponent',
                'api/components/NumericDecimalsComponent',
                'api/components/FractionOptionsComponent',
                'api/components/NumericalIntervalComponent',
                'api/components/MissingValueComponent',
                'api/components/DeleteAttributeComponent',
              ]
            },
            {
              type: 'category',
              label: 'New Attribute Creator',
              items: [
                 'api/components/NewAttributeComponent',
                 'api/components/FormulaInputComponent',
              ]
            },
            'api/components/AttributeDisplaySetting',
            'api/components/RandomSampleComponent',
            'api/components/ModelFunctionsWrapper',
          ]
        },
        {
            type: 'category',
            label: 'Plot Settings',
            items: ['api/components/PlotSettingComponent']
        },
        {
            type: 'category',
            label: 'Accessibility',
            items: ['api/components/AccessibilitySettingsComponent']
        },
        {
          type: 'category',
          label: 'Common Utilities',
          items: [
            'api/components/common/ContextMenuWrapper',
            'api/components/common/GlobalContextMenu',
            'api/components/common/HistogramContextMenu',
            'api/components/common/AnnotationContextMenu',
            'api/components/common/StdDeviationsContextMenu',
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'Core Plotting (dynplot)',
      items: [
        'api/dynplot/PlotView',
        'api/dynplot/AxisView',
        'api/dynplot/topMarginView',
        'api/dynplot/rightMarginView',
        'api/dynplot/PlotShaper',
        'api/dynplot/iconStyler',
        'api/dynplot/PlotMeasure',
        {
          type: 'category',
          label: 'Utils',
          items: [
            'api/dynplot/utils/plotUtil',
            'api/dynplot/utils/axisUtil',
            'api/dynplot/utils/ContextMenuUtil',
          ],
        },
        {
          type: 'category',
          label: 'Plot Elements',
          items: [
            'api/dynplot/plotElement/PlotElement',
            {
              type: 'category',
              label: 'DotPlot Family',
              items: [
                'api/dynplot/plotElement/DotPlotBase',
                'api/dynplot/plotElement/DotPlotElement',
                {
                  type: 'category',
                  label: 'Line Graphs (extends DotPlotBase)',
                  items: [
                    'api/dynplot/plotElement/LineGraphElement',
                    'api/dynplot/plotElement/LineGraphSingleElement',
                    'api/dynplot/plotElement/LineAndCategoryElement',
                  ]
                }
              ]
            },
            {
              type: 'category',
              label: 'Bar Chart Family',
              items: [
                'api/dynplot/plotElement/BarElement',
                'api/dynplot/plotElement/FreqBarElement',
                'api/dynplot/plotElement/BarOfSumsElement',
                'api/dynplot/plotElement/BarOfMeansElement',
                'api/dynplot/plotElement/StretchedBarElement',
                'api/dynplot/plotElement/ValueBarElement',
              ]
            },
            {
              type: 'category',
              label: 'Histogram Family',
              items: [
                'api/dynplot/plotElement/HistogramElement',
                'api/dynplot/plotElement/FreqHistogramElement',
                'api/dynplot/plotElement/PercentHistogramElement',
                'api/dynplot/plotElement/ProportionHistogramElement',
              ]
            },
            {
              type: 'category',
              label: 'Box Plot Family',
              items: [
                'api/dynplot/plotElement/BoxPlotElement',
                'api/dynplot/plotElement/StandardBoxPlotElement',
                'api/dynplot/plotElement/OutlierBoxPlotElement',
                'api/dynplot/plotElement/BoxAndDotPlotElement',
              ]
            },
            'api/dynplot/plotElement/MapElement',
            {
              type: 'category',
              label: 'Annotation Elements',
              items: [
                'api/dynplot/plotElement/AnnotateElement',
                'api/dynplot/plotElement/AnnotationLinePencil',
                'api/dynplot/plotElement/AnnotationRectangle',
                'api/dynplot/plotElement/AnnotationCircle',
                'api/dynplot/plotElement/AnnotationArrow',
                'api/dynplot/plotElement/AnnotationStraightLine',
                'api/dynplot/plotElement/AnnotationText',
                'api/dynplot/plotElement/AnnotationImage',
              ]
            },
          ],
        }
      ],
    },
    {
      type: 'category',
      label: 'Core Data (dynDataset)',
      items: [{ type: 'autogenerated', dirName: 'api/dynDataset' }],
    },
  ],
};

export default sidebars;
