name: Trigger Documentation Build

on:
  release:
    types: [published]

jobs:
  trigger-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger docs repository workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.DOCS_REPO_TOKEN }}" \
            https://api.github.com/repos/${{ secrets.DOCS_REPO }}/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}' 